### ISSUE TITLE
Change Primary Font to Inter for better Vietnamese Display

### ISSUE THREAD

**Issue by vnphanquang** [sveltevietnam/learn.svelte.dev#45]
## Vấn đề

Hiện tại `learn.svelte.dev` load font `Overpass` từ `@sveltejs/site-kit`:

https://github.com/sveltevietnam/learn.svelte.dev/blob/4e158c762f62e3c8888a8cd109c8f6f16ee08bf1/src/routes/+layout.svelte#L8

Font này không đc thiết kế cho tiếng Việt, gây ra một số lỗi hiển thị, đặc biệt trên ios safari. Lỗi này đc [báo từ discord](https://discord.com/channels/1066621936546877450/1161146343276937326/1161532023861678180).

## Giải pháp

Ta sẽ chuyển sang dùng Inter. Có 2 cách:

1. Load trực tiếp từ [google font](https://fonts.google.com/specimen/Inter), nhanh gọn nhưng ko tối ưu hóa lắm
2. Tự host font theo giải pháp `sveltevietnam.dev` đang dùng. [Xem tại đây](https://github.com/sveltevietnam/sveltevietnam.dev/blob/2c6bc809fc3583bf6c52fd2ff1e725630063012d/sites/www/src/lib/client/styles/app.css#L1). Cụ thể hơn giải pháp này đã chia nhỏ font ra thành nhiều tập hơn con với kí tự dành riêng cho mỗi ngôn ngữ. Trong trường hợp của chúng ta browser sẽ chỉ cần load `inter-latin` và `inter-vietnamese`, giúp cải thiện tốc độ load của trang

```[tasklist]
### Tasks
- [ ] Load `Inter` sử dụng một trong hai giải pháp trên
- [ ] Khai báo `font-family` mặc định ghi đè lên `Overpass`
```

**Comment by tobedecided0601** [comment]
mình nghĩ cách 2 sẽ được hơn vì mình có sẵn font rồi, với cả load từ server mình sẽ nhanh hơn so với việc load từ cdn của google
