### ISSUE TITLE
thiếu khoản trắng ở mục handle

### ISSUE THREAD

**Issue by trongnguyen24** [sveltevietnam/learn.svelte.dev#83]
ở đây mình thấy bị thiếu một khoản cách "...trái ngược vớiAPI routes"

https://learn.sveltevietnam.dev/tutorial/handle
![image](https://github.com/sveltevietnam/learn.svelte.dev/assets/6469345/c18ab9fd-35af-479f-b05b-c5ef5cd910fe)

**Comment by vnphanquang** [comment]
@trongnguyen24 cảm ơn bạn. Đây là cơ hôi tốt nếu bạn muốn đóng góp vào mã nguồn. Bạn có muốn nhận issue này luôn ko?

**Comment by trongnguyen24** [comment]
cám ơn anh @vnphanquang, em nghĩ mình có thể sửa những phần typo nhỏ như vầy.

**Comment by vnphanquang** [comment]
@trongnguyen24 vậy bạn cứ thử nhé. Nếu cần hỗ trợ hoặc thảo luận bạn có thể tham gia vào discord ở [kênh #translation](https://discord.com/channels/1066621936546877450/1161146343276937326)

**Comment by vnphanquang** [comment]
done via https://github.com/sveltevietnam/learn.svelte.dev/pull/86
